### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DarkMistofWoods** [DarkMistofWoods/universum#1]
- [ ] add hidden third parameter for terms: category
- [ ] lexicon terms should sort by category by default, then abc order therein
- [ ] add translator functionality that uses included list of terms
- [ ] add name generator functionality that uses included list of terms

**Comment by DarkMistofWoods** [comment]
- [ ] Improve name generator (maybe using python & ML on a web server)
- [ ] Optimize and clarify phonetic and grammatical rules
- [ ] Overhaul vocabulary to fit the above optimized rules

**Comment by DarkMistofWoods** [comment]
- [ ] change class container to tool-section class and adjust javascript and CSS in accordance

**Comment by DarkMistofWoods** [comment]
- [ ] handle user progress initialization on the server (cloud function?)
- [ ]

**Comment by DarkMistofWoods** [comment]
- [ ] In the userProgress data structure, each lesson has a boolean value indicating whether the user has completed it. I want to make it so the only nodes shown in color are from the completed lessons/submodules/modules (i.e., a lesson node only shows if the lesson is completed, a submodule node only shows once all of its lessons are completed, and a module node only shows once all of its submodules are completed). The only other nodes that are shown are the nodes that are directly connected to the colored nodes, and they will be grey, indicating that they have not yet been completed.

**Comment by DarkMistofWoods** [comment]
- [ ] user should be able to change their email address in settings
- [ ] vocabulary lessons should focus on root word memorization and association with their respective concepts or ideas
