### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DarkMistofWoods** [DarkMistofWoods/universum#3]
- [ ] if the user is logged in an they click any of the buttons on the home page they should be directed to the dashboard
- [ ] fix settings.js reference error
- [ ] add saving functionality to save button

**Comment by DarkMistofWoods** [comment]
### Navigation ### 
- [ ] make it so the nav line between any two points on the nav circle is only drawn once
- [ ] make cursor 'pointer' when hovering over the center of the nav circle
- [ ] text should have a radial gradient that is color-quaternary>transparent rather than a rounded box
- [ ] mobile interaction should be more intuitive
- [ ]

**Comment by DarkMistofWoods** [comment]
### Lessons ### 
- [ ]

**Comment by DarkMistofWoods** [comment]
### Current/Community Progress ### 
- [ ] node network visualization depicting the user's strengths and weaknesses
- [ ] does not display nodes for which no information yet exists

**Comment by DarkMistofWoods** [comment]
### Settings ### 
- [ ] implement download data function
- [ ] implement delete data function

**Comment by DarkMistofWoods** [comment]
### Achievements ### 
- [ ] needs to display all incomplete or in-progress achievements

**Comment by DarkMistofWoods** [comment]
### Dashboard ###
- [ ] current progress tracker should be scrollable and sort modules/submodules by order of in progress, completed, and not started

**Comment by DarkMistofWoods** [comment]
### Official Corpus ###
- [ ] replaces the 'community progress' page
- [ ] automatically displays winning entries from the 'translation trial' challenge
- [ ]

**Comment by DarkMistofWoods** [comment]
### Recommendation System ### 
- [ ] use ensemble methods? not sure what the load will be on the server
